alias ls="ls --color=auto"
source /home/hello/kasa/ambarella/build/env/armv7ahf-linaro-gcc.env
export UTEKI_ROOT=/home/hello/kasa/ambarella/uteki
export SYSROOT=/home/hello/kasa/ambarella/out/hawthorn/fakeroot
export GOOS=linux
export GOARCH=arm
export GOARM=7
cd
